CREATE TABLE "User" (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Email VARCHAR(100) UNIQUE,
    PhoneNumber VARCHAR2(20)
);

CREATE TABLE Vendor (
    VendorId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CompanyName VARCHAR2(100),
    Address VARCHAR2(200),
    DateJoin DATE,
    CONSTRAINT vendorid_fk FOREIGN KEY (VendorId) REFERENCES "User"(id)
);

CREATE TABLE Customer (
    CustomerId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MembershipNo VARCHAR2(50),
    DateJoin DATE,
    CONSTRAINT customer_fk FOREIGN KEY (CustomerId) REFERENCES "User"(Id)
);

CREATE TABLE Staff (
    StaffId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Position VARCHAR2(50),
    Salary NUMBER(10,2),
    DateHired DATE,
    ManagedBy NUMBER,
    CONSTRAINT user_fk FOREIGN KEY (StaffId) REFERENCES "User"(Id),
    CONSTRAINT manager_fk FOREIGN KEY (ManagedBy) REFERENCES Staff(StaffId)
);

CREATE TABLE Item (
    ItemId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Price NUMBER(10,2),
    CurrentStock NUMBER,
    LastUpdateDateTime TIMESTAMP
);


CREATE TABLE Cloth (
    ClothId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ClothSize VARCHAR2(100),
    IsAdultOrChild VARCHAR2(10),
    Sex VARCHAR2(10),
    CONSTRAINT cloth_fk FOREIGN KEY (ClothId) REFERENCES Item(ItemId)
);

CREATE TABLE Sale (
    SaleId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SaleDateTime TIMESTAMP,
    TotalPrice NUMBER(10,2),
    CustomerId NUMBER NOT NULL,
    StaffId NUMBER NOT NULL,
    CONSTRAINT customerid_fk FOREIGN KEY (CustomerId) REFERENCES Customer(CustomerId),
    CONSTRAINT staffid_fk FOREIGN KEY (StaffId) REFERENCES Staff(StaffId)
);



CREATE TABLE SaleDetail (
    SaleDetailId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SaleId NUMBER NOT NULL,
    ItemId NUMBER NOT NULL,
    Quantity NUMBER NOT NULL,
    FinalPrice NUMBER(10,2),
    CONSTRAINT saledetail_fk FOREIGN KEY (SaleId) REFERENCES Sale(SaleId),
    CONSTRAINT detailitem_fk FOREIGN KEY (ItemId) REFERENCES Item(ItemId)
);


CREATE TABLE ItemCategory (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL
);

CREATE TABLE PurchaseOrder (
    PurchaseOrderId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VendorId NUMBER,
    StaffId NUMBER, 
    OrderDateTime TIMESTAMP,
    InvoiceNo VARCHAR2(50),
    TotalPrice NUMBER(10,2),
    CONSTRAINT vendor_fk FOREIGN KEY (VendorId) REFERENCES Vendor(VendorId),
    CONSTRAINT stafforder_fk FOREIGN KEY (StaffId) REFERENCES Staff(StaffId)
);


CREATE TABLE PurchaseOrderDetail (
    PODetailId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PurchaseOrderId NUMBER, 
    ItemId NUMBER,
    Quantity NUMBER, 
    CONSTRAINT podetail_fk FOREIGN KEY (PurchaseOrderId) REFERENCES PurchaseOrder(PurchaseOrderId),
    CONSTRAINT itemidpd_fk FOREIGN KEY (ItemId) REFERENCES Item(ItemId)
);

CREATE TABLE Cart (
    CartId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CustomerId NUMBER,
    ItemId NUMBER,
    CONSTRAINT cartcustomer_fk FOREIGN KEY (CustomerId) REFERENCES Customer(CustomerId),
    CONSTRAINT cartitem_fk FOREIGN KEY (ItemId) REFERENCES Item(ItemId)
);

ALTER TABLE Cart
RENAME TO CART_TABLE;

SELECT *
FROM USERS;

INSERT INTO USERS (Name, Email, PhoneNumber) VALUES
('Ahmad Zulkifli', 'ahmadz@gmail.com', '0123456789','Zul@7889'),
('Siti Aminah', 'sitiaminah@yahoo.com', '0172233445','Mina_44779'),
('Tan Wei Ming', 'wm.tan@gmail.com', '0198877665','Wei#77255'), 
('Muthu Arumugam', 'muthu_v@gmail.com', '0134455667','Arum*23900'),
('Nurul Izzah', 'izzah.n@gmail.com', '0111234567','Arum*23900'), 
('Chong Mei Ling', 'meiling_c@gmail.com', '0165566778','Mei%23446'),
('Ravi Kumar', 'ravik@hotmail.com', '0129988776','Kumar!78995'), 
('Zaiton Sameon', 'zaiton.s@gmail.com', '0142233112','Same@90029'),
('Lim Guan Eng', 'ge.lim@gmail.com', '0173344556','Guan@46885'),
('Fatimah Abu', 'fatimah@outlook.com', '0185566443','Tima_34567'),
('Wong Kar Wai', 'wongkw@gmail.com', '0125544332','Kar@49930'),
('Sangeetha Nair', 'sangee@gmail.com', '0112233441','Geetha*22113'),
('Hafiz Suip', 'hafiz.s@gmail.com', '0192233114','Pis_789444'), 
('Ng Yeow Shin', 'ngys@yahoo.com', '0161122334','Yeos@99544'),
('Siti Sarah', 'sarah.siti@gmail.com', '0177788990','Sara@67334'), 
('Jason Leong', 'jasonl@gmail.com', '0122211334','Sara@67334'),
('Azizulhasni Awang', 'azizul@gmail.com', '0133344551','Awang_87328'),
('Michelle Yeoh', 'm.yeoh@gmail.com', '0169988771','Mike@35966'),
('Badrul Hisham', 'badrulh@gmail.com', '0123344559','Hish@34789'), 
('Lee Zii Jia', 'ziijia@gmail.com', '0194455662','Jia@90234'),
('Nur Irdina', 'idnabilah@gmail.com', '0119988772','Dina@349663'), 
('Khairul Jami', 'khairulj@gmail.com', '0143344556','Jami#96549'),
('Zulaikha', 'sitinoor.z@gmail.com', '0182233445','Zu@ika345'), 
('Farah Ann', 'farah.a@gmail.com', '0123322114','Ann_34853'),
('Ariff Aziz', 'ariff@gmail.com', '0174455668','Aziz@55400'), 
('Low Wee Wern', 'lowww@gmail.com', '0197766554','Wern@95377'),
('Firdaus Mansor', 'firdaus.m@gmail.com', '0136655443','Daus_96432'), 
('Nadia', 'nadiaaaa@gmail.com', '0168877665','Dania@459205'),
('Amirul Afiq', 'amirul@gmail.com', '0112211335','Apiq_27634'), 
('Iman Syamilah', 'stephanie@gmail.com', '0129988443','Syamil@24865');

INSERT INTO VENDOR (CompanyName, Address, DateJoin) VALUES
('Batik Indah Corp', 'Kilang 34, Pasir Puteh, Kelantan', TO_DATE('15-01-2020','DD-MM-YYYY')),
('KL Textiles', 'B-2-1, Block B, Megan Avenue 1, 50450 Kuala Lumpur', TO_DATE('20-02-2020','DD-MM-YYYY')),
('Penang Fabrics', '123-A, Lebuh Chulia, 10100 Georgetown, Pulau Pinang', TO_DATE('05-03-2020','DD-MM-YYYY')),
('JB Garments', 'No 8, Jalan Wong Ah Fook, 80000 Johor Bahru, Johor', TO_DATE('12-03-2020','DD-MM-YYYY')),
('Silk Road MY', 'B-2-1, Block B, Megan Avenue 1, 50450 Kuala Lumpur', TO_DATE('01-04-2020','DD-MM-YYYY')),
('Mega Fashion', 'Lot 45, Kawasan Perindustrian Shah Alam, 40000 Selangor', TO_DATE('18-05-2020','DD-MM-YYYY')),
('Urban Wear', 'No 33, Jalan SS21/37, Damansara Utama, 47400 Selangor', TO_DATE('22-06-2020','DD-MM-YYYY')),
('Traditional Style', 'Lot G-12, Bangsar Village II, 59100 Kuala Lumpur', TO_DATE('10-07-2021','DD-MM-YYYY')),
('Modern Clothier', 'No 5, Jalan Hang Jebat, 75200 Melaka', TO_DATE('04-08-2022','DD-MM-YYYY')),
('Cotton King', 'No 15, Jalan Petaling, 50000 Kuala Lumpur', TO_DATE('29-09-2022','DD-MM-YYYY')),
('Malaya Threads', 'Plot 18, Bayan Lepas Free Trade Zone, 11900 Pulau Pinang', TO_DATE('15-10-2022','DD-MM-YYYY')),
('Kaiti Si', '22-1, Jalan Telawi 3, Bangsar Baru, 59100 Kuala Lumpur', TO_DATE('03-11-2021','DD-MM-YYYY')),
('Borneo Weave', 'No 88, Jalan Gaya, 88000 Kota Kinabalu, Sabah', TO_DATE('12-12-2022','DD-MM-YYYY')),
('East Coast Batik', 'No 4, Jalan Pantai Jaya, 20400 Kuala Terengganu, Terengganu', TO_DATE('01-08-2023','DD-MM-YYYY')),
('Royal Songket', 'Lot 10, Kompleks Kraftangan, Jalan Conlay, 50450 Kuala Lumpur', TO_DATE('25-01-2021','DD-MM-YYYY')),
('Heritage Silks', 'No 56, Armenian Street, 10200 Pulau Pinang', TO_DATE('14-02-2023','DD-MM-YYYY')),
('Perak Garment', 'No 10, Jalan Leong Boon Swee, 30000 Ipoh, Perak', TO_DATE('03-03-2024','DD-MM-YYYY')),
('Zenith Apparel', 'Level 5, Menara IMC, No 8 Jalan Sultan Ismail, 50250 KL', TO_DATE('21-03-2024','DD-MM-YYYY')),
('Kuching Cottons', 'No 12, Main Bazaar, 93000 Kuching, Sarawak', TO_DATE('10-01-2024','DD-MM-YYYY')),
('Seremban Textiles', 'No 2, Jalan Tuanku Munawir, 70000 Seremban, Negeri Sembilan', TO_DATE('11-04-2023','DD-MM-YYYY')),
('Kuantan Fabrics', 'Lot 102, Kawasan Perindustrian Semambu, 25350 Kuantan, Pahang', TO_DATE('05-02-2021','DD-MM-YYYY')),
('Perlis Threads', 'No 14, Jalan Besar, 01000 Kangar, Perlis', TO_DATE('30-05-2023','DD-MM-YYYY')),
('Kedah Weaving', 'No 3, Jalan Teluk Wanjah, 05200 Alor Setar, Kedah', TO_DATE('15-06-2024','DD-MM-YYYY')),
('Putrajaya Wear', 'Presint 15, 62050 Putrajaya', TO_DATE('07-04-2023','DD-MM-YYYY')),
('Ampang Fashion', 'No 45, Jalan Ampang, 50450 Kuala Lumpur', TO_DATE('19-08-2025','DD-MM-YYYY')),
('Subang Stitches', 'No 1, Jalan SS15/4, 47500 Subang Jaya, Selangor', TO_DATE('09-12-2025','DD-MM-YYYY')),
('Cyberjaya Cloth', 'Block 3730, Persiaran APEC, 63000 Cyberjaya', TO_DATE('10-01-2025','DD-MM-YYYY')),
('Rawang Textiles', 'Lot 9, Kawasan Perindustrian Rawang, 48000 Selangor', TO_DATE('20-11-2025','DD-MM-YYYY')),
('Muar Garments', 'No 50, Jalan Maharani, 84000 Muar, Johor', TO_DATE('12-05-2024','DD-MM-YYYY')),
('Klang Valley Silk', 'No 18, Jalan Kapar, 41400 Klang, Selangor', TO_DATE('28-12-2023','DD-MM-YYYY'));

INSERT INTO staff (position, salary, dateHired) VALUES ('Sales Associate', 2500, TO_DATE('12-05-2020', 'DD-MM-YYYY'));
INSERT INTO staff (position, salary, dateHired) VALUES ('Cashier', 2300, TO_DATE('20-11-2021', 'DD-MM-YYYY'));
INSERT INTO staff (position, salary, dateHired) VALUES ('Store Manager', 5800, TO_DATE('15-01-2020', 'DD-MM-YYYY'));
INSERT INTO staff (position, salary, dateHired) VALUES ('Stock Associate', 2200, TO_DATE('05-03-2024', 'DD-MM-YYYY'));
INSERT INTO staff (position, salary, dateHired) VALUES ('Visual Merchandiser', 3500, TO_DATE('10-08-2020', 'DD-MM-YYYY'));
INSERT INTO staff (position, salary, dateHired) VALUES ('Sales Associate', 2500, TO_DATE('01-12-2023', 'DD-MM-YYYY'));
INSERT INTO staff (position, salary, dateHired) VALUES ('Security', 2800, TO_DATE('25-10-2019', 'DD-MM-YYYY'));
INSERT INTO staff (position, salary, dateHired) VALUES ('Inventory Clerk', 2600, TO_DATE('14-04-2022', 'DD-MM-YYYY'));
INSERT INTO staff (position, salary, dateHired) VALUES ('Assistant Manager', 4500, TO_DATE('20-06-2020', 'DD-MM-YYYY'));
INSERT INTO staff (position, salary, dateHired) VALUES ('Sales Associate', 2500, TO_DATE('10-01-2025', 'DD-MM-YYYY'));
INSERT INTO staff (position, salary, dateHired) VALUES ('Cashier', 2300, TO_DATE('15-02-2020', 'DD-MM-YYYY'));
INSERT INTO staff (position, salary, dateHired) VALUES ('Stockroom Manager', 3800, TO_DATE('12-03-2022', 'DD-MM-YYYY'));
INSERT INTO staff (position, salary, dateHired) VALUES ('Sales Associate', 2500, TO_DATE('22-07-2021', 'DD-MM-YYYY'));
INSERT INTO staff (position, salary, dateHired) VALUES ('Visual Merchandiser', 3500, TO_DATE('18-09-2025', 'DD-MM-YYYY'));
INSERT INTO staff (position, salary, dateHired) VALUES ('Stock Associate', 2200, TO_DATE('12-12-2022', 'DD-MM-YYYY'));
INSERT INTO staff (position, salary, dateHired) VALUES ('Cashier', 2300, TO_DATE('05-01-2026', 'DD-MM-YYYY'));
INSERT INTO staff (position, salary, dateHired) VALUES ('Sales Associate', 2500, TO_DATE('30-11-2024', 'DD-MM-YYYY'));
INSERT INTO staff (position, salary, dateHired) VALUES ('Security', 2800, TO_DATE('05-05-2021', 'DD-MM-YYYY'));
INSERT INTO staff (position, salary, dateHired) VALUES ('Inventory Clerk', 2600, TO_DATE('20-08-2023', 'DD-MM-YYYY'));
INSERT INTO staff (position, salary, dateHired) VALUES ('Sales Associate', 2500, TO_DATE('15-11-2024', 'DD-MM-YYYY'));
INSERT INTO staff (position, salary, dateHired) VALUES ('Stock Associate', 2200, TO_DATE('20-01-2020', 'DD-MM-YYYY'));
INSERT INTO staff (position, salary, dateHired) VALUES ('Cashier', 2300, TO_DATE('10-09-2022', 'DD-MM-YYYY'));
INSERT INTO staff (position, salary, dateHired) VALUES ('Sales Associate', 2500, TO_DATE('28-02-2021', 'DD-MM-YYYY'));
INSERT INTO staff (position, salary, dateHired) VALUES ('Visual Merchandiser', 3500, TO_DATE('14-06-2024', 'DD-MM-YYYY'));
INSERT INTO staff (position, salary, dateHired) VALUES ('Stock Associate', 2200, TO_DATE('30-03-2025', 'DD-MM-YYYY'));
INSERT INTO staff (position, salary, dateHired) VALUES ('Sales Associate', 2500, TO_DATE('12-12-2021', 'DD-MM-YYYY'));
INSERT INTO staff (position, salary, dateHired) VALUES ('Cashier', 2300, TO_DATE('05-04-2023', 'DD-MM-YYYY'));
INSERT INTO staff (position, salary, dateHired) VALUES ('Sales Associate', 2500, TO_DATE('01-09-2024', 'DD-MM-YYYY'));
INSERT INTO staff (position, salary, dateHired) VALUES ('Stock Associate', 2200, TO_DATE('02-01-2026', 'DD-MM-YYYY'));
INSERT INTO staff (position, salary, dateHired) VALUES ('Sales Associate', 2500, TO_DATE('07-07-2022', 'DD-MM-YYYY'));

INSERT INTO Item (Name, Price, currentStock, LastUpdateDateTime) VALUES ('Slim Fit Denim Jeans', 129.00, 45, TO_TIMESTAMP('12-05-2025 10:30:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO Item (Name, Price, currentStock, LastUpdateDateTime) VALUES ('Oversized Graphic T-Shirt', 59.90, 120, TO_TIMESTAMP('05-01-2026 14:20:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO Item (Name, Price, currentStock, LastUpdateDateTime) VALUES ('Floral Summer Dress', 89.00, 30, TO_TIMESTAMP('15-08-2024 09:15:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO Item (Name, Price, currentStock, LastUpdateDateTime) VALUES ('Cotton Chino Pants', 110.00, 65, TO_TIMESTAMP('20-12-2025 16:45:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO Item (Name, Price, currentStock, LastUpdateDateTime) VALUES ('Leather Biker Jacket', 299.00, 12, TO_TIMESTAMP('02-11-2024 11:00:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO Item (Name, Price, currentStock, LastUpdateDateTime) VALUES ('Plain White Polo Tee', 45.00, 200, TO_TIMESTAMP('08-01-2026 08:30:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO Item (Name, Price, currentStock, LastUpdateDateTime) VALUES ('High-Waist Cargo Pants', 95.00, 55, TO_TIMESTAMP('22-07-2025 13:10:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO Item (Name, Price, currentStock, LastUpdateDateTime) VALUES ('Hoodie Midnight Blue', 149.00, 40, TO_TIMESTAMP('25-12-2024 15:50:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO Item (Name, Price, currentStock, LastUpdateDateTime) VALUES ('Formal Office Shirt', 79.90, 85, TO_TIMESTAMP('30-09-2025 10:00:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO Item (Name, Price, currentStock, LastUpdateDateTime) VALUES ('Kid’s Cotton Pajamas', 39.00, 150, TO_TIMESTAMP('02-01-2026 09:40:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO Item (Name, Price, currentStock, LastUpdateDateTime) VALUES ('Denim Mini Skirt', 69.00, 25, TO_TIMESTAMP('14-03-2025 12:20:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO Item (Name, Price, currentStock, LastUpdateDateTime) VALUES ('V-Neck Wool Sweater', 120.00, 18, TO_TIMESTAMP('10-10-2024 17:15:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO Item (Name, Price, currentStock, LastUpdateDateTime) VALUES ('Linen Button-Down Shirt', 99.00, 35, TO_TIMESTAMP('05-06-2025 11:30:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO Item (Name, Price, currentStock, LastUpdateDateTime) VALUES ('Puffer Winter Vest', 189.00, 10, TO_TIMESTAMP('20-01-2024 14:00:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO Item (Name, Price, currentStock, LastUpdateDateTime) VALUES ('Activewear Leggings', 75.00, 90, TO_TIMESTAMP('18-11-2025 08:00:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO Item (Name, Price, currentStock, LastUpdateDateTime) VALUES ('Striped Long Sleeve Tee', 49.90, 110, TO_TIMESTAMP('10-01-2026 13:45:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO Item (Name, Price, currentStock, LastUpdateDateTime) VALUES ('Ankle Boots Brown', 159.00, 15, TO_TIMESTAMP('28-02-2025 16:00:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO Item (Name, Price, currentStock, LastUpdateDateTime) VALUES ('Checked Flannel Shirt', 85.00, 48, TO_TIMESTAMP('12-09-2024 10:20:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO Item (Name, Price, currentStock, LastUpdateDateTime) VALUES ('Silk Evening Scarf', 55.00, 20, TO_TIMESTAMP('01-05-2025 09:00:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO Item (Name, Price, currentStock, LastUpdateDateTime) VALUES ('Classic Trench Coat', 350.00, 8, TO_TIMESTAMP('05-12-2024 12:00:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO Item (Name, Price, currentStock, LastUpdateDateTime) VALUES ('Jogger Sweatpants Grey', 65.00, 70, TO_TIMESTAMP('03-01-2026 15:30:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO Item (Name, Price, currentStock, LastUpdateDateTime) VALUES ('Knitted Cardigan', 135.00, 22, TO_TIMESTAMP('19-04-2025 11:10:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO Item (Name, Price, currentStock, LastUpdateDateTime) VALUES ('Snapback Baseball Cap', 29.90, 250, TO_TIMESTAMP('09-01-2026 10:50:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO Item (Name, Price, currentStock, LastUpdateDateTime) VALUES ('Pleated Midi Skirt', 89.00, 33, TO_TIMESTAMP('08-08-2025 14:25:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO Item (Name, Price, currentStock, LastUpdateDateTime) VALUES ('Sleeveless Blouse White', 59.00, 60, TO_TIMESTAMP('25-01-2025 08:15:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO Item (Name, Price, currentStock, LastUpdateDateTime) VALUES ('Canvas Tote Bag', 15.00, 500, TO_TIMESTAMP('11-01-2026 07:00:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO Item (Name, Price, currentStock, LastUpdateDateTime) VALUES ('Straight Leg Trousers', 115.00, 42, TO_TIMESTAMP('30-07-2024 13:40:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO Item (Name, Price, currentStock, LastUpdateDateTime) VALUES ('Quilted Handbag Black', 199.00, 14, TO_TIMESTAMP('15-12-2025 11:55:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO Item (Name, Price, currentStock, LastUpdateDateTime) VALUES ('Crew Neck Sweatshirt', 89.90, 55, TO_TIMESTAMP('20-06-2024 15:20:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO Item (Name, Price, currentStock, LastUpdateDateTime) VALUES ('Patterned Silk Tie', 49.00, 30, TO_TIMESTAMP('03-03-2025 09:10:00', 'DD-MM-YYYY HH24:MI:SS'));

INSERT INTO Cloth (ClothSize, IsAdultOrChild, Sex) VALUES ('M', 'Adult', 'Male');
INSERT INTO Cloth (ClothSize, IsAdultOrChild, Sex) VALUES ('S', 'Adult', 'Female');
INSERT INTO Cloth (ClothSize, IsAdultOrChild, Sex) VALUES ('XL', 'Adult', 'Unisex');
INSERT INTO Cloth (ClothSize, IsAdultOrChild, Sex) VALUES ('XS', 'Child', 'Female');
INSERT INTO Cloth (ClothSize, IsAdultOrChild, Sex) VALUES ('L', 'Adult', 'Male');
INSERT INTO Cloth (ClothSize, IsAdultOrChild, Sex) VALUES ('M', 'Adult', 'Female');
INSERT INTO Cloth (ClothSize, IsAdultOrChild, Sex) VALUES ('S', 'Child', 'Male');
INSERT INTO Cloth (ClothSize, IsAdultOrChild, Sex) VALUES ('XXL', 'Adult', 'Male');
INSERT INTO Cloth (ClothSize, IsAdultOrChild, Sex) VALUES ('L', 'Adult', 'Female');
INSERT INTO Cloth (ClothSize, IsAdultOrChild, Sex) VALUES ('M', 'Child', 'Unisex');
INSERT INTO Cloth (ClothSize, IsAdultOrChild, Sex) VALUES ('S', 'Adult', 'Male');
INSERT INTO Cloth (ClothSize, IsAdultOrChild, Sex) VALUES ('XL', 'Adult', 'Female');
INSERT INTO Cloth (ClothSize, IsAdultOrChild, Sex) VALUES ('XS', 'Adult', 'Female');
INSERT INTO Cloth (ClothSize, IsAdultOrChild, Sex) VALUES ('L', 'Child', 'Male');
INSERT INTO Cloth (ClothSize, IsAdultOrChild, Sex) VALUES ('M', 'Adult', 'Unisex');
INSERT INTO Cloth (ClothSize, IsAdultOrChild, Sex) VALUES ('S', 'Adult', 'Female');
INSERT INTO Cloth (ClothSize, IsAdultOrChild, Sex) VALUES ('XL', 'Adult', 'Male');
INSERT INTO Cloth (ClothSize, IsAdultOrChild, Sex) VALUES ('M', 'Child', 'Female');
INSERT INTO Cloth (ClothSize, IsAdultOrChild, Sex) VALUES ('XXL', 'Adult', 'Unisex');
INSERT INTO Cloth (ClothSize, IsAdultOrChild, Sex) VALUES ('S', 'Child', 'Female');
INSERT INTO Cloth (ClothSize, IsAdultOrChild, Sex) VALUES ('L', 'Adult', 'Male');
INSERT INTO Cloth (ClothSize, IsAdultOrChild, Sex) VALUES ('M', 'Adult', 'Female');
INSERT INTO Cloth (ClothSize, IsAdultOrChild, Sex) VALUES ('XL', 'Child', 'Male');
INSERT INTO Cloth (ClothSize, IsAdultOrChild, Sex) VALUES ('S', 'Adult', 'Unisex');
INSERT INTO Cloth (ClothSize, IsAdultOrChild, Sex) VALUES ('L', 'Adult', 'Female');
INSERT INTO Cloth (ClothSize, IsAdultOrChild, Sex) VALUES ('M', 'Adult', 'Male');
INSERT INTO Cloth (ClothSize, IsAdultOrChild, Sex) VALUES ('XS', 'Child', 'Unisex');
INSERT INTO Cloth (ClothSize, IsAdultOrChild, Sex) VALUES ('XL', 'Adult', 'Male');
INSERT INTO Cloth (ClothSize, IsAdultOrChild, Sex) VALUES ('S', 'Adult', 'Female');
INSERT INTO Cloth (ClothSize, IsAdultOrChild, Sex) VALUES ('M', 'Child', 'Male');

INSERT INTO Customer (MembershipNo, DateJoin) VALUES ('M1001', TO_DATE('01-01-2024','DD-MM-YYYY'));
INSERT INTO Customer (MembershipNo, DateJoin) VALUES ('M1002', TO_DATE('05-01-2025','DD-MM-YYYY'));
INSERT INTO Customer (MembershipNo, DateJoin) VALUES ('M1003', TO_DATE('10-01-2024','DD-MM-YYYY'));
INSERT INTO Customer (MembershipNo, DateJoin) VALUES ('M1004', TO_DATE('15-01-2025','DD-MM-YYYY'));
INSERT INTO Customer (MembershipNo, DateJoin) VALUES ('M1005', TO_DATE('20-01-2024','DD-MM-YYYY'));
INSERT INTO Customer (MembershipNo, DateJoin) VALUES ('M1006', TO_DATE('01-02-2025','DD-MM-YYYY'));
INSERT INTO Customer (MembershipNo, DateJoin) VALUES ('M1007', TO_DATE('05-02-2024','DD-MM-YYYY'));
INSERT INTO Customer (MembershipNo, DateJoin) VALUES ('M1008', TO_DATE('10-02-2025','DD-MM-YYYY'));
INSERT INTO Customer (MembershipNo, DateJoin) VALUES ('M1009', TO_DATE('15-02-2024','DD-MM-YYYY'));
INSERT INTO Customer (MembershipNo, DateJoin) VALUES ('M1010', TO_DATE('20-02-2025','DD-MM-YYYY'));
INSERT INTO Customer (MembershipNo, DateJoin) VALUES ('M1011', TO_DATE('01-03-2024','DD-MM-YYYY'));
INSERT INTO Customer (MembershipNo, DateJoin) VALUES ('M1012', TO_DATE('05-03-2025','DD-MM-YYYY'));
INSERT INTO Customer (MembershipNo, DateJoin) VALUES ('M1013', TO_DATE('10-03-2024','DD-MM-YYYY'));
INSERT INTO Customer (MembershipNo, DateJoin) VALUES ('M1014', TO_DATE('15-03-2025','DD-MM-YYYY'));
INSERT INTO Customer (MembershipNo, DateJoin) VALUES ('M1015', TO_DATE('20-03-2024','DD-MM-YYYY'));
INSERT INTO Customer (MembershipNo, DateJoin) VALUES ('M1016', TO_DATE('01-04-2025','DD-MM-YYYY'));
INSERT INTO Customer (MembershipNo, DateJoin) VALUES ('M1017', TO_DATE('05-04-2024','DD-MM-YYYY'));
INSERT INTO Customer (MembershipNo, DateJoin) VALUES ('M1018', TO_DATE('10-04-2025','DD-MM-YYYY'));
INSERT INTO Customer (MembershipNo, DateJoin) VALUES ('M1019', TO_DATE('15-04-2024','DD-MM-YYYY'));
INSERT INTO Customer (MembershipNo, DateJoin) VALUES ('M1020', TO_DATE('20-04-2025','DD-MM-YYYY'));
INSERT INTO Customer (MembershipNo, DateJoin) VALUES ('M1021', TO_DATE('01-05-2024','DD-MM-YYYY'));
INSERT INTO Customer (MembershipNo, DateJoin) VALUES ('M1022', TO_DATE('05-05-2025','DD-MM-YYYY'));
INSERT INTO Customer (MembershipNo, DateJoin) VALUES ('M1023', TO_DATE('10-05-2024','DD-MM-YYYY'));
INSERT INTO Customer (MembershipNo, DateJoin) VALUES ('M1024', TO_DATE('15-05-2025','DD-MM-YYYY'));
INSERT INTO Customer (MembershipNo, DateJoin) VALUES ('M1025', TO_DATE('20-05-2024','DD-MM-YYYY'));
INSERT INTO Customer (MembershipNo, DateJoin) VALUES ('M1026', TO_DATE('01-06-2025','DD-MM-YYYY'));
INSERT INTO Customer (MembershipNo, DateJoin) VALUES ('M1027', TO_DATE('05-06-2024','DD-MM-YYYY'));
INSERT INTO Customer (MembershipNo, DateJoin) VALUES ('M1028', TO_DATE('10-06-2025','DD-MM-YYYY'));
INSERT INTO Customer (MembershipNo, DateJoin) VALUES ('M1029', TO_DATE('15-06-2024','DD-MM-YYYY'));
INSERT INTO Customer (MembershipNo, DateJoin) VALUES ('M1030', TO_DATE('20-06-2024','DD-MM-YYYY'));

INSERT INTO Sale (SaleDateTime, TotalPrice, CustomerId, StaffId) VALUES (TO_TIMESTAMP('01-01-2026 10:00','DD-MM-YYYY HH24:MI'), 120,1,2);
INSERT INTO Sale (SaleDateTime, TotalPrice, CustomerId, StaffId) VALUES (TO_TIMESTAMP('01-01-2026 11:00','DD-MM-YYYY HH24:MI'), 180,2,2);
INSERT INTO Sale (SaleDateTime, TotalPrice, CustomerId, StaffId) VALUES (TO_TIMESTAMP('01-01-2026 12:00','DD-MM-YYYY HH24:MI'), 90,7,17);
INSERT INTO Sale (SaleDateTime, TotalPrice, CustomerId, StaffId) VALUES (TO_TIMESTAMP('02-01-2026 10:30','DD-MM-YYYY HH24:MI'), 200,1,10);
INSERT INTO Sale (SaleDateTime, TotalPrice, CustomerId, StaffId) VALUES (TO_TIMESTAMP('02-01-2026 11:30','DD-MM-YYYY HH24:MI'), 150,23,22);
INSERT INTO Sale (SaleDateTime, TotalPrice, CustomerId, StaffId) VALUES (TO_TIMESTAMP('03-01-2026 09:45','DD-MM-YYYY HH24:MI'), 75,11,17);
INSERT INTO Sale (SaleDateTime, TotalPric,e CustomerId, StaffId) VALUES (TO_TIMESTAMP('03-01-2026 10:45','DD-MM-YYYY HH24:MI'), 220,7,10);
INSERT INTO Sale (SaleDateTime, TotalPrice, CustomerId, StaffId) VALUES (TO_TIMESTAMP('03-01-2026 14:00','DD-MM-YYYY HH24:MI'), 160,8,13);
INSERT INTO Sale (SaleDateTime, TotalPrice, CustomerId, StaffId) VALUES (TO_TIMESTAMP('04-01-2026 09:30','DD-MM-YYYY HH24:MI'), 130,19,13);
INSERT INTO Sale (SaleDateTime, TotalPrice, CustomerId, StaffId) VALUES (TO_TIMESTAMP('04-01-2026 11:00','DD-MM-YYYY HH24:MI'), 190,19,2);
INSERT INTO Sale (SaleDateTime, TotalPrice, CustomerId, StaffId) VALUES (TO_TIMESTAMP('05-01-2026 10:15','DD-MM-YYYY HH24:MI'), 140,15,22);
INSERT INTO Sale (SaleDateTime, TotalPrice, CustomerId, StaffId) VALUES (TO_TIMESTAMP('05-01-2026 13:30','DD-MM-YYYY HH24:MI'), 210,23,17);
INSERT INTO Sale (SaleDateTime, TotalPrice, CustomerId, StaffId) VALUES (TO_TIMESTAMP('06-01-2026 09:00','DD-MM-YYYY HH24:MI'), 80,13,10);
INSERT INTO Sale (SaleDateTime, TotalPrice, CustomerId, StaffId) VALUES (TO_TIMESTAMP('06-01-2026 10:00','DD-MM-YYYY HH24:MI'), 170,15,10);
INSERT INTO Sale (SaleDateTime, TotalPrice, CustomerId, StaffId) VALUES (TO_TIMESTAMP('06-01-2026 11:30','DD-MM-YYYY HH24:MI'), 155,15,2);
INSERT INTO Sale (SaleDateTime, TotalPrice, CustomerId, StaffId) VALUES (TO_TIMESTAMP('07-01-2026 10:00','DD-MM-YYYY HH24:MI'), 95,16,22);
INSERT INTO Sale (SaleDateTime, TotalPrice, CustomerId, StaffId) VALUES (TO_TIMESTAMP('07-01-2026 12:00','DD-MM-YYYY HH24:MI'), 230,7,13);
INSERT INTO Sale (SaleDateTime, TotalPrice, CustomerId, StaffId) VALUES (TO_TIMESTAMP('07-01-2026 15:00','DD-MM-YYYY HH24:MI'), 165,8,13);
INSERT INTO Sale (SaleDateTime, TotalPrice, CustomerId, StaffId) VALUES (TO_TIMESTAMP('08-01-2026 09:30','DD-MM-YYYY HH24:MI'), 110,19,10);
INSERT INTO Sale (SaleDateTime, TotalPrice, CustomerId, StaffId) VALUES (TO_TIMESTAMP('08-01-2026 11:45','DD-MM-YYYY HH24:MI'), 185,21,17);
INSERT INTO Sale (SaleDateTime, TotalPrice, CustomerId, StaffId) VALUES (TO_TIMESTAMP('09-01-2026 10:00','DD-MM-YYYY HH24:MI'), 125,21,17);
INSERT INTO Sale (SaleDateTime, TotalPrice, CustomerId, StaffId) VALUES (TO_TIMESTAMP('09-01-2026 12:30','DD-MM-YYYY HH24:MI'), 205,22,13);
INSERT INTO Sale (SaleDateTime, TotalPrice, CustomerId, StaffId) VALUES (TO_TIMESTAMP('10-01-2026 09:00','DD-MM-YYYY HH24:MI'), 90,23,22);
INSERT INTO Sale (SaleDateTime, TotalPrice, CustomerId, StaffId) VALUES (TO_TIMESTAMP('10-01-2026 10:30','DD-MM-YYYY HH24:MI'), 160,11,17);,
INSERT INTO Sale (SaleDateTime, TotalPrice, CustomerId, StaffId) VALUES (TO_TIMESTAMP('11-01-2026 11:00','DD-MM-YYYY HH24:MI'), 175,19,17);
INSERT INTO Sale (SaleDateTime, TotalPrice, CustomerId, StaffId) VALUES (TO_TIMESTAMP('11-01-2026 13:00','DD-MM-YYYY HH24:MI'), 220,1,2);
INSERT INTO Sale (SaleDateTime, TotalPrice, CustomerId, StaffId) VALUES (TO_TIMESTAMP('12-01-2026 09:45','DD-MM-YYYY HH24:MI'), 100,22,10);
INSERT INTO Sale (SaleDateTime, TotalPrice, CustomerId, StaffId) VALUES (TO_TIMESTAMP('12-01-2026 11:15','DD-MM-YYYY HH24:MI'), 195,16,10);
INSERT INTO Sale (SaleDateTime, TotalPrice, CustomerId, StaffId) VALUES (TO_TIMESTAMP('13-01-2026 10:00','DD-MM-YYYY HH24:MI'), 145,13,2);
INSERT INTO Sale (SaleDateTime, TotalPrice, CustomerId, StaffId) VALUES (TO_TIMESTAMP('13-01-2026 12:00','DD-MM-YYYY HH24:MI'), 210,30,22);

INSERT INTO SaleDetail (SaleId, ItemId,Quantity, FinalPrice) VALUES (1, 4, 2, 120);
INSERT INTO SaleDetail (SaleId, ItemId, Quantity, FinalPrice) VALUES (2, 22, 3, 180);
INSERT INTO SaleDetail (SaleId, ItemId, Quantity, FinalPrice) VALUES (3, 15, 1, 90);
INSERT INTO SaleDetail (SaleId, ItemId, Quantity, FinalPrice) VALUES (4, 17, 4, 200);
INSERT INTO SaleDetail (SaleId, ItemId, Quantity, FinalPrice) VALUES (5, 5, 3, 150);
INSERT INTO SaleDetail (SaleId, ItemId, Quantity, FinalPrice) VALUES (6, 7, 1, 75);
INSERT INTO SaleDetail (SaleId, ItemId, Quantity, FinalPrice) VALUES (7, 1, 4, 220);
INSERT INTO SaleDetail (SaleId, ItemId, Quantity, FinalPrice) VALUES (8, 28, 2, 160);
INSERT INTO SaleDetail (SaleId, ItemId, Quantity, FinalPrice) VALUES (9, 23, 2, 130);
INSERT INTO SaleDetail (SaleId, ItemId, Quantity, FinalPrice) VALUES (10, 2,  3, 190);
INSERT INTO SaleDetail (SaleId, ItemId, Quantity, FinalPrice) VALUES (11, 10, 2, 140);
INSERT INTO SaleDetail (SaleId, ItemId, Quantity, FinalPrice) VALUES (12, 11, 5, 210);
INSERT INTO SaleDetail (SaleId, ItemId, Quantity, FinalPrice) VALUES (13, 19,  1, 80);
INSERT INTO SaleDetail (SaleId, ItemId, Quantity, FinalPrice) VALUES (14, 22, 2, 170);
INSERT INTO SaleDetail (SaleId, ItemId, Quantity, FinalPrice) VALUES (15, 6, 3, 155);
INSERT INTO SaleDetail (SaleId, ItemId, Quantity, FinalPrice) VALUES (16, 3, 1, 95);
INSERT INTO SaleDetail (SaleId, ItemId, Quantity, FinalPrice) VALUES (17, 4, 4, 230);
INSERT INTO SaleDetail (SaleId, ItemId, Quantity, FinalPrice) VALUES (18, 15, 3, 165);
INSERT INTO SaleDetail (SaleId, ItemId, Quantity, FinalPrice) VALUES (19, 13, 2, 110);
INSERT INTO SaleDetail (SaleId, ItemId, Quantity, FinalPrice) VALUES (20, 2, 3, 185);
INSERT INTO SaleDetail (SaleId, ItemId, Quantity, FinalPrice) VALUES (21, 8, 2, 125);
INSERT INTO SaleDetail (SaleId, ItemId, Quantity, FinalPrice) VALUES (22, 26,  5, 205);
INSERT INTO SaleDetail (SaleId, ItemId, Quantity, FinalPrice) VALUES (23, 22, 1, 90);
INSERT INTO SaleDetail (SaleId, ItemId, Quantity, FinalPrice) VALUES (24, 18, 2, 160);
INSERT INTO SaleDetail (SaleId, ItemId, Quantity, FinalPrice) VALUES (25, 13, 3, 175);
INSERT INTO SaleDetail (SaleId, ItemId, Quantity, FinalPrice) VALUES (26, 3, 4, 220);
INSERT INTO SaleDetail (SaleId, ItemId, Quantity, FinalPrice) VALUES (27, 7, 2, 100);
INSERT INTO SaleDetail (SaleId, ItemId ,Quantity, FinalPrice) VALUES (28, 22, 3, 195);
INSERT INTO SaleDetail (SaleId, ItemId, Quantity, FinalPrice) VALUES (29, 25, 2, 145);
INSERT INTO SaleDetail (SaleId, ItemId, Quantity, FinalPrice) VALUES (30, 2, 5, 210);

INSERT INTO PurchaseOrder (VendorId, StaffId, OrderDateTime, InvoiceNo, TotalPrice) VALUES (1, 3, TO_DATE('15-01-2025 09:00', 'DD-MM-YYYY HH24:MI'), 'PO-2025-001', 1500.00);
INSERT INTO PurchaseOrder (VendorId, StaffId, OrderDateTime, InvoiceNo, TotalPrice) VALUES (2, 9, TO_DATE('18-01-2025 10:30', 'DD-MM-YYYY HH24:MI'), 'PO-2025-002', 2450.50);
INSERT INTO PurchaseOrder (VendorId, StaffId, OrderDateTime, InvoiceNo, TotalPrice) VALUES (3, 12, TO_DATE('05-02-2025 14:00', 'DD-MM-YYYY HH24:MI'), 'PO-2025-003', 3100.00);
INSERT INTO PurchaseOrder (VendorId, StaffId, OrderDateTime, InvoiceNo, TotalPrice) VALUES (4, 3, TO_DATE('12-02-2025 11:15', 'DD-MM-YYYY HH24:MI'), 'PO-2025-004', 1200.75);
INSERT INTO PurchaseOrder (VendorId, StaffId, OrderDateTime, InvoiceNo, TotalPrice) VALUES (5, 9, TO_DATE('01-03-2025 08:45', 'DD-MM-YYYY HH24:MI'), 'PO-2025-005', 4500.00);
INSERT INTO PurchaseOrder (VendorId, StaffId, OrderDateTime, InvoiceNo, TotalPrice) VALUES (6, 21, TO_DATE('10-03-2025 16:20', 'DD-MM-YYYY HH24:MI'), 'PO-2025-006', 980.00);
INSERT INTO PurchaseOrder (VendorId, StaffId, OrderDateTime, InvoiceNo, TotalPrice) VALUES (7, 3, TO_DATE('22-03-2025 09:30', 'DD-MM-YYYY HH24:MI'), 'PO-2025-007', 5600.00);
INSERT INTO PurchaseOrder (VendorId, StaffId, OrderDateTime, InvoiceNo, TotalPrice) VALUES (8, 9, TO_DATE('05-04-2025 13:00', 'DD-MM-YYYY HH24:MI'), 'PO-2025-008', 2150.00);
INSERT INTO PurchaseOrder (VendorId, StaffId, OrderDateTime, InvoiceNo, TotalPrice) VALUES (9, 12, TO_DATE('15-04-2025 10:00', 'DD-MM-YYYY HH24:MI'), 'PO-2025-009', 1800.25);
INSERT INTO PurchaseOrder (VendorId, StaffId, OrderDateTime, InvoiceNo, TotalPrice) VALUES (10, 21, TO_DATE('02-05-2025 15:45', 'DD-MM-YYYY HH24:MI'), 'PO-2025-010', 7200.00);
INSERT INTO PurchaseOrder (VendorId, StaffId, OrderDateTime, InvoiceNo, TotalPrice) VALUES (12, 9, TO_DATE('01-06-2025 09:15', 'DD-MM-YYYY HH24:MI'), 'PO-2025-012', 2900.00);
INSERT INTO PurchaseOrder (VendorId, StaffId, OrderDateTime, InvoiceNo, TotalPrice) VALUES (13, 12, TO_DATE('12-06-2025 14:20', 'DD-MM-YYYY HH24:MI'), 'PO-2025-013', 4100.80);
INSERT INTO PurchaseOrder (VendorId, StaffId, OrderDateTime, InvoiceNo, TotalPrice) VALUES (14, 3, TO_DATE('04-07-2025 10:50', 'DD-MM-YYYY HH24:MI'), 'PO-2025-014', 1100.00);
INSERT INTO PurchaseOrder (VendorId, StaffId, OrderDateTime, InvoiceNo, TotalPrice) VALUES (15, 9, TO_DATE('20-07-2025 16:00', 'DD-MM-YYYY HH24:MI'), 'PO-2025-015', 550.00);
INSERT INTO PurchaseOrder (VendorId, StaffId, OrderDateTime, InvoiceNo, TotalPrice) VALUES (16, 12, TO_DATE('11-08-2025 09:30', 'DD-MM-YYYY HH24:MI'), 'PO-2025-016', 3200.00);
INSERT INTO PurchaseOrder (VendorId, StaffId, OrderDateTime, InvoiceNo, TotalPrice) VALUES (17, 21, TO_DATE('25-08-2025 11:00', 'DD-MM-YYYY HH24:MI'), 'PO-2025-017', 2800.40);
INSERT INTO PurchaseOrder (VendorId, StaffId, OrderDateTime, InvoiceNo, TotalPrice) VALUES (18, 3, TO_DATE('05-09-2025 13:15', 'DD-MM-YYYY HH24:MI'), 'PO-2025-018', 6100.00);
INSERT INTO PurchaseOrder (VendorId, StaffId, OrderDateTime, InvoiceNo, TotalPrice) VALUES (19, 9, TO_DATE('18-09-2025 10:20', 'DD-MM-YYYY HH24:MI'), 'PO-2025-019', 1900.00);
INSERT INTO PurchaseOrder (VendorId, StaffId, OrderDateTime, InvoiceNo, TotalPrice) VALUES (20, 12, TO_DATE('02-10-2025 14:40', 'DD-MM-YYYY HH24:MI'), 'PO-2025-020', 4450.00);
INSERT INTO PurchaseOrder (VendorId, StaffId, OrderDateTime, InvoiceNo, TotalPrice) VALUES (21, 21, TO_DATE('15-10-2025 08:30', 'DD-MM-YYYY HH24:MI'), 'PO-2025-021', 1250.60);
INSERT INTO PurchaseOrder (VendorId, StaffId, OrderDateTime, InvoiceNo, TotalPrice) VALUES (22, 3, TO_DATE('01-11-2025 12:00', 'DD-MM-YYYY HH24:MI'), 'PO-2025-022', 890.00);
INSERT INTO PurchaseOrder (VendorId, StaffId, OrderDateTime, InvoiceNo, TotalPrice) VALUES (23, 9, TO_DATE('20-11-2025 15:10', 'DD-MM-YYYY HH24:MI'), 'PO-2025-023', 3700.00);
INSERT INTO PurchaseOrder (VendorId, StaffId, OrderDateTime, InvoiceNo, TotalPrice) VALUES (24, 12, TO_DATE('05-12-2025 09:45', 'DD-MM-YYYY HH24:MI'), 'PO-2025-024', 2100.00);
INSERT INTO PurchaseOrder (VendorId, StaffId, OrderDateTime, InvoiceNo, TotalPrice) VALUES (25, 21, TO_DATE('15-12-2025 11:25', 'DD-MM-YYYY HH24:MI'), 'PO-2025-025', 5400.20);
INSERT INTO PurchaseOrder (VendorId, StaffId, OrderDateTime, InvoiceNo, TotalPrice) VALUES (26, 3, TO_DATE('28-12-2025 14:00', 'DD-MM-YYYY HH24:MI'), 'PO-2025-026', 1600.00);
INSERT INTO PurchaseOrder (VendorId, StaffId, OrderDateTime, InvoiceNo, TotalPrice) VALUES (27, 9, TO_DATE('02-01-2026 10:30', 'DD-MM-YYYY HH24:MI'), 'PO-2026-001', 3300.50);
INSERT INTO PurchaseOrder (VendorId, StaffId, OrderDateTime, InvoiceNo, TotalPrice) VALUES (28, 12, TO_DATE('05-01-2026 09:15', 'DD-MM-YYYY HH24:MI'), 'PO-2026-002', 2700.00);
INSERT INTO PurchaseOrder (VendorId, StaffId, OrderDateTime, InvoiceNo, TotalPrice) VALUES (29, 21, TO_DATE('08-01-2026 13:45', 'DD-MM-YYYY HH24:MI'), 'PO-2026-003', 1950.00);
INSERT INTO PurchaseOrder (VendorId, StaffId, OrderDateTime, InvoiceNo, TotalPrice) VALUES (30, 3, TO_DATE('10-01-2026 16:00', 'DD-MM-YYYY HH24:MI'), 'PO-2026-004', 4200.00);

INSERT INTO PurchaseOrderDetail (PurchaseOrderId, ItemId, Quantity) VALUES (1, 1, 100);
INSERT INTO PurchaseOrderDetail (PurchaseOrderId, ItemId, Quantity) VALUES (2, 2, 150);
INSERT INTO PurchaseOrderDetail (PurchaseOrderId, ItemId, Quantity) VALUES (3, 3, 200);
INSERT INTO PurchaseOrderDetail (PurchaseOrderId, ItemId, Quantity) VALUES (4, 4, 80);
INSERT INTO PurchaseOrderDetail (PurchaseOrderId, ItemId, Quantity) VALUES (5, 5, 250);
INSERT INTO PurchaseOrderDetail (PurchaseOrderId, ItemId, Quantity) VALUES (6, 6, 120);
INSERT INTO PurchaseOrderDetail (PurchaseOrderId, ItemId, Quantity) VALUES (7, 7, 300);
INSERT INTO PurchaseOrderDetail (PurchaseOrderId, ItemId, Quantity) VALUES (8, 8, 180);
INSERT INTO PurchaseOrderDetail (PurchaseOrderId, ItemId, Quantity) VALUES (9, 9, 140);
INSERT INTO PurchaseOrderDetail (PurchaseOrderId, ItemId, Quantity) VALUES (10, 10, 140);
INSERT INTO PurchaseOrderDetail (PurchaseOrderId, ItemId, Quantity) VALUES (11, 11, 122);
INSERT INTO PurchaseOrderDetail (PurchaseOrderId, ItemId, Quantity) VALUES (12, 12, 160);
INSERT INTO PurchaseOrderDetail (PurchaseOrderId, ItemId, Quantity) VALUES (13, 13, 135);
INSERT INTO PurchaseOrderDetail (PurchaseOrderId, ItemId, Quantity) VALUES (14, 14, 90);
INSERT INTO PurchaseOrderDetail (PurchaseOrderId, ItemId, Quantity) VALUES (15, 15, 60);
INSERT INTO PurchaseOrderDetail (PurchaseOrderId, ItemId, Quantity) VALUES (16, 16, 128);
INSERT INTO PurchaseOrderDetail (PurchaseOrderId, ItemId, Quantity) VALUES (17, 17, 124);
INSERT INTO PurchaseOrderDetail (PurchaseOrderId, ItemId, Quantity) VALUES (18, 18, 132);
INSERT INTO PurchaseOrderDetail (PurchaseOrderId, ItemId, Quantity) VALUES (19, 19, 111);
INSERT INTO PurchaseOrderDetail (PurchaseOrderId, ItemId, Quantity) VALUES (20, 20, 127);
INSERT INTO PurchaseOrderDetail (PurchaseOrderId, ItemId, Quantity) VALUES (21, 21, 113);
INSERT INTO PurchaseOrderDetail (PurchaseOrderId, ItemId, Quantity) VALUES (22, 22, 70);
INSERT INTO PurchaseOrderDetail (PurchaseOrderId, ItemId, Quantity) VALUES (23, 23, 119);
INSERT INTO PurchaseOrderDetail (PurchaseOrderId, ItemId, Quantity) VALUES (24, 24, 121);
INSERT INTO PurchaseOrderDetail (PurchaseOrderId, ItemId, Quantity) VALUES (25, 25, 134);
INSERT INTO PurchaseOrderDetail (PurchaseOrderId, ItemId, Quantity) VALUES (26, 26, 117);
INSERT INTO PurchaseOrderDetail (PurchaseOrderId, ItemId, Quantity) VALUES (27, 27, 126);
INSERT INTO PurchaseOrderDetail (PurchaseOrderId, ItemId, Quantity) VALUES (28, 28, 123);
INSERT INTO PurchaseOrderDetail (PurchaseOrderId, ItemId, Quantity) VALUES (29, 29, 115);
INSERT INTO PurchaseOrderDetail (PurchaseOrderId, ItemId, Quantity) VALUES (30, 30, 129);

COMMIT;