select * from item;

UPDATE ITEM SET NAME = 'Slim Fit Denim Jeans', PRICE = 129, CURRENTSTOCK = 43, LASTUPDATEDATETIME = SYSDATE WHERE ITEMID = 1;

commit;

CREATE TABLE Cart (
    CartId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CustomerId NUMBER,
    ItemId NUMBER,
    CONSTRAINT cartcustomer_fk FOREIGN KEY (CustomerId) REFERENCES Customer(CustomerId),
    CONSTRAINT cartitem_fk FOREIGN KEY (ItemId) REFERENCES Item(ItemId)
);

ALTER TABLE PURCHASEORDER
ADD STATUS VARCHAR2(255);

ALTER TABLE CARTITEM 
ADD QUANTITY NUMBER;

ALTER TABLE Cart
RENAME TO CartItem;

select * from cartitem;
select * from users;
select * from staff;
select * from item order by name;
select * from vendor;
select * from purchaseorder;
select * from purchaseorderdetail;

select last_insert_id();

SELECT ID, NAME, EMAIL, PHONENUMBER, ROLE FROM users WHERE ROLE = 'staff' OR ROLE = 'admin';

delete from purchaseorder
where purchaseorderid in (221,222);

update users
set role = LOWER(role);

desc cartitem;
desc purchaseorder;

SELECT CARTITEM.ITEMID, SUM(ITEM.PRICE) OVER() AS TOTAL_PRICE FROM CARTITEM JOIN ITEM ON CARTITEM.ITEMID = ITEM.ITEMID WHERE CARTITEM.CUSTOMERID = 1;

INSERT INTO cartitem
VALUES(1, 1,1);

INSERT INTO CARTITEM (CUSTOMERID, ITEMID) VALUES (1, 1);