SELECT
    USERS.NAME,
    COUNT(SALE.SALEID),
    SUM(SALE.TOTALPRICE)
FROM USERS
JOIN STAFF ON USERS.ID = STAFF.STAFFID
LEFT JOIN SALE ON STAFF.STAFFID = SALE.STAFFID
WHERE sale.saledatetime BETWEEN TRUNC(SYSDATE, 'MM') AND ADD_MONTHS(TRUNC(SYSDATE, 'MM'), 1)
GROUP BY USERS.NAME
ORDER BY 2 DESC;

SELECT * FROM SALE;